# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import DataDescriptionHandler_pb2 as DataDescriptionHandler__pb2


class DataDescripionHandlerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadMessages = channel.unary_unary(
                '/DataDescripionH.DataDescripionHandler/UploadMessages',
                request_serializer=DataDescriptionHandler__pb2.MessageUrlRecordStream.SerializeToString,
                response_deserializer=DataDescriptionHandler__pb2.Empty.FromString,
                )
        self.UploadImage = channel.unary_unary(
                '/DataDescripionH.DataDescripionHandler/UploadImage',
                request_serializer=DataDescriptionHandler__pb2.MessageUrlRecordImage.SerializeToString,
                response_deserializer=DataDescriptionHandler__pb2.Empty.FromString,
                )


class DataDescripionHandlerServicer(object):
    """The greeting service definition.
    """

    def UploadMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataDescripionHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadMessages,
                    request_deserializer=DataDescriptionHandler__pb2.MessageUrlRecordStream.FromString,
                    response_serializer=DataDescriptionHandler__pb2.Empty.SerializeToString,
            ),
            'UploadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=DataDescriptionHandler__pb2.MessageUrlRecordImage.FromString,
                    response_serializer=DataDescriptionHandler__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataDescripionH.DataDescripionHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataDescripionHandler(object):
    """The greeting service definition.
    """

    @staticmethod
    def UploadMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataDescripionH.DataDescripionHandler/UploadMessages',
            DataDescriptionHandler__pb2.MessageUrlRecordStream.SerializeToString,
            DataDescriptionHandler__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataDescripionH.DataDescripionHandler/UploadImage',
            DataDescriptionHandler__pb2.MessageUrlRecordImage.SerializeToString,
            DataDescriptionHandler__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
